apiVersion: v1
kind: Node
metadata:
  name: 10.240.79.157
  labels:
    name: my-first-k8s-node
spec:
  null: null
status:
  conditions:
    - message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory|KubeletHasNoDiskPressure|KubeletHasSufficientPID|KubeletReady
      status: "False"
      type: MemoryPressure # DiskPressure|PIDPressure|NetworkUnavailable|OutOfDisk|Ready
    - status: "False" # or "Unknown" for a period of pod-eviction-timeout (default: 5 mins) API initiatespod eviction
      type: Ready
      reason: KubeletReady
  addresses:
    - address: 192.168.1.13
      type: InternalIP
    - address: skylark
      type: Hostname
  capacity: # Describes the resources available on the node
    pods: 100
    cpu: 8
    memory: 2Gi  
  allocatable: # The amount of resources on a Node that is available to be consumed by normal Pods
    pods: 80
    cpu: 7
    memory: 1Gi
  