apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: cm9vdAo=          # echo root | basenc --base64
  mongo-password: cm9vdDEyMwo=  # echo root123 | basenc --base64
